import { Link } from "react-router-dom";

function codeOfConduct() {
  return (
    <div className="terms-container">
      {/* Stripe Navigation */}
      <div className="stripe-nav">
        <div className="stripe-options">
          <span className="terms-option">
            <Link to="/terms">Terms of Service</Link>
          </span>
          <span className="terms-option">
            <Link to="/privacypolicy">Privacy Policy</Link>
          </span>
          <span className="terms-option">
            <Link to="/cookiespolicy">Cookie Policy</Link>
          </span>
          <span className="terms-option">
            <Link to="/codeofconduct">Code of Conduct</Link>
          </span>
        </div>
      </div>

      {/* Main Content */}
      <div className="main-content">
        <h1 className="terms-title">Code of Conduct</h1>
        <h2 className="terms-subtitle">Whatever Guidelines</h2>
        <p className="terms-description">
          Whatever brings designers together to share their work, talk shop, and
          find new opportunities. Weve created this code of conduct to ensure
          Whatever is the best place to discover great design and the designers
          behind it.
        </p>

        <div className="terms-body">
          <h2>
            As a member of the Whatever community, you agree to the following
            guidelines:
          </h2>
          <p className="terms-paragraph">
            SHOT GUIDELINES Only upload design work. Dont share promotional
            videos, commercials, or tutorials. Dont share anything that isnt
            graphic design work. For more details on what you can share on
            Whatever, head here. Do not upload work or images with watermarks or
            other obfuscating markings. Do not use Whatever Shots to advertise
            your product or service. If you’re interested in advertising on
            Whatever, you can learn more here. Do not use Whatever Shots to
            promote your job listing. If you’re interested in posting a Job on
            Whatever, you can learn more here. Do not post inappropriate
            content. Do not post content that is illegal, pornographic, violent,
            mature in content, or gratuitously or overly sexual, racist, sexist,
            or otherwise offensive. We realize that nudity can be a gray area.
            We aim to keep Whatever PG-13. Do not post inflammatory content. For
            example: name-calling, preaching, ranting, stirring up controversy,
            or venting frustrations. Per our Terms of Service, Whatever has
            final say over whether content is appropriate. Only share work that
            you have permission to share. Do not post work created by other
            designers. Do not share content that is wholly generated by AI. When
            creating content with AI assistance, it is recommended to
            acknowledge the contribution of AI in your Shot description. Do not
            share work that contains copyrighted or trademarked content. Do not
            share work you are contractually obligated not to, for example,
            without client permission or under NDA. Dont take credit for others
            work. Dont plagiarize work by other designers. If your work is
            inspired by other work on Whatever, create a Rebound. Please link
            back to Whatever when posting Whatever content elsewhere and do not
            use design work without permission. Ensure you have the appropriate
            licenses to use music or other stock assets in Shots.
          </p>
          <h2>COMMUNITY GUIDELINES</h2>
          <p className="terms-paragraph">
            Only use social gestures for genuine engagement. Do not use likes,
            follows, and other disingenuous social gestures to draw attention to
            your account. Do not use automations (like bots or scripts) to like,
            save, follow, or disingenuously engage on the platform. Comments
            should be constructive. Do not leave comments that are short on
            substance to draw attention to your own account. Do not leave links
            or direct people to your own work when leaving comments. When
            providing criticism or feedback to other Whatever members, be
            helpful, not mean. Messages should be constructive for the
            recipient. Do not use messages to spam Whatever users. Examples of
            spam include: Advertising your services or products Inappropriate or
            profane messages Deceptive or misleading messages Nonsense or test
            messages Mass messages Impersonating an individual or organization
            Consider leaving observations or questions about a Shot (Example:
            Nice work! What font is that? Etc.) as a comment rather than sending
            a message.
          </p>
          <h2>ACCOUNT GUIDELINES</h2>
          <p className="terms-paragraph">
            Personal accounts are for the work of an individual designer only.
            User accounts may not be used to share the work of a team,
            collective, community or any other group of individuals. Users may
            not share personal accounts. Each user may only have a single
            personal account and may not create multiple personal accounts for
            different categories of design work. Team profiles are for design
            agencies and in-house design teams only. All team members must work
            for your agency or design team. Team owners must not receive
            compensation in exchange for team seats. Do not abuse profile
            features. Do not replace your name with an email address, website
            URL, or keywords. For example: Dan Thornett • Logos • Branding •
            Graphic Design Do not include the following information in either
            the description or masthead image of your profile: Profanity,
            offensive content or hurtful language. Known false information,
            including onsite statistics, follower counts or other misleading
            information.
          </p>
          <h2>HIRING GUIDELINES</h2>
          <p className="terms-paragraph">
            All work inquiries on Whatever must be for paid design work. No
            design contests or spec work are allowed. Job listings must clearly
            define the offered role, be up-to-date and follow all other Job
            Board Best Practices and Policies. Do not send low-quality Hiring
            messages: Ensure that the designer youre contacting is a good fit
            for your job. Personalize the messages you senddont send boilerplate
            messages. They tend to feel impersonal and lack the detail necessary
            to be appealing. Include the project or position details in your
            first message. Messages that don’t mention a work inquiry may not
            reach the designers inbox. Discrimination based on race, ethnicity,
            gender, sexual orientation, age, disability, or religion will not be
            tolerated.
          </p>
        </div>
      </div>
    </div>
  );
}

export default codeOfConduct;
